<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"><!-- 
 %l

body
:lang(fa) { direction: rtl; font-size: 100%; font-family: Tahoma, Roya, sans-serif; float: right; }
:lang(he) { direction: rtl; float: right; }
 --></style>
</head><body>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="http://www.imdb.com/title/tt0427152/plotsummary">http://www.imdb.com/title/tt0427152/plotsummary</a></p>

<blockquote id="error">
<p><b>Read Error</b></p>
</blockquote>

<p id="sysmsg">The system returned: <i>(104) Connection reset by peer</i></p>

<p>An error condition occurred while reading data from the network.  Please retry your request.</p>

<p>Your cache administrator is <a href="mailto:nisl@hust?subject=CacheErrorInfo%20-%20ERR_READ_ERROR&amp;body=CacheHost%3A%20proxy%0D%0AErrPage%3A%20ERR_READ_ERROR%0D%0AErr%3A%20(104)%20Connection%20reset%20by%20peer%0D%0ATimeStamp%3A%20Mon,%2020%20Dec%202010%2008%3A00%3A34%20GMT%0D%0A%0D%0AClientIP%3A%20218.199.102.165%0D%0AServerIP%3A%2072.21.211.32%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Ftitle%2Ftt0427152%2Fplotsummary%20HTTP%2F1.1%0AUser-Agent%3A%20Mozilla%2F4.0%20(compatible%3B%20MSIE%206.0%3B%20Windows%20NT%205.1)%0D%0AHost%3A%20www.imdb.com%0D%0AAccept-Encoding%3A%20gzip,%20deflate%0D%0A%0D%0A%0D%0A">nisl@hust</a>.</p>
<br>
</div>

<hr>
<div id="footer">
<p>Generated Mon, 20 Dec 2010 08:00:34 GMT by proxy (squid/3.0.STABLE18)</p>
<!-- ERR_READ_ERROR -->
</div>
</body></html>
